name: PR pipeline

on:
  pull_request:
    branches:
      - main
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  stg-pipeline:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest]

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-
      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -U -r requirements.txt

      - name: Run Unit Tests & Coverage
        run: |
          pip install coverage
          coverage run -m unittest discover tests/unit "*_test.py"
          coverage report

      - name: Deploy integration test [staging environment]
        run: |
          dbx deploy  --deployment-file=conf/stg-deployment.yml --jobs=databricks-notebook-cicd-github-actions-stg-integration-test --assets-only
  
      - name: Run integration test [staging environment]
        run: |
          dbx launch  --deployment-file=conf/stg-deployment.yml --job=databricks-notebook-cicd-github-actions-stg-integration-test --from-assets --trace

      - name: Deploy the job.
        run: |
          dbx deploy --deployment-file=conf/stg-deployment.yml --no-rebuild

      - name: Restart the job.
        run: |
          dbx launch --job=databricks-notebook-cicd-github-actions-stg --existing-runs=cancel